<?php

namespace ContainerXV4xLKH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_8HzjRMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._8HzjRM' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._8HzjRM'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'usuario' => ['privates', '.errored..service_locator._8HzjRM.App\\Entity\\Usuarios', NULL, 'Cannot autowire service ".service_locator._8HzjRM": it references class "App\\Entity\\Usuarios" but no such service exists.'],
        ], [
            'usuario' => 'App\\Entity\\Usuarios',
        ]);
    }
}
