<?php

namespace ContainerXV4xLKH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_WiLjZAAService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.wiLjZAA' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.wiLjZAA'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'App\\Controller\\UsuariosController::delete' => ['privates', '.service_locator._8HzjRM', 'get_ServiceLocator_8HzjRMService', true],
            'App\\Controller\\UsuariosController::edit' => ['privates', '.service_locator._8HzjRM', 'get_ServiceLocator_8HzjRMService', true],
            'App\\Controller\\UsuariosController::index' => ['privates', '.service_locator.n4RRAH8', 'get_ServiceLocator_N4RRAH8Service', true],
            'App\\Controller\\UsuariosController::show' => ['privates', '.service_locator._8HzjRM', 'get_ServiceLocator_8HzjRMService', true],
            'App\\Kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'App\\Kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'kernel::loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel::terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
            'App\\Controller\\UsuariosController:delete' => ['privates', '.service_locator._8HzjRM', 'get_ServiceLocator_8HzjRMService', true],
            'App\\Controller\\UsuariosController:edit' => ['privates', '.service_locator._8HzjRM', 'get_ServiceLocator_8HzjRMService', true],
            'App\\Controller\\UsuariosController:index' => ['privates', '.service_locator.n4RRAH8', 'get_ServiceLocator_N4RRAH8Service', true],
            'App\\Controller\\UsuariosController:show' => ['privates', '.service_locator._8HzjRM', 'get_ServiceLocator_8HzjRMService', true],
            'kernel:loadRoutes' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:registerContainerConfiguration' => ['privates', '.service_locator.C9JCBPC', 'get_ServiceLocator_C9JCBPCService', true],
            'kernel:terminate' => ['privates', '.service_locator.beq5mCo', 'get_ServiceLocator_Beq5mCoService', true],
        ], [
            'App\\Controller\\UsuariosController::delete' => '?',
            'App\\Controller\\UsuariosController::edit' => '?',
            'App\\Controller\\UsuariosController::index' => '?',
            'App\\Controller\\UsuariosController::show' => '?',
            'App\\Kernel::loadRoutes' => '?',
            'App\\Kernel::registerContainerConfiguration' => '?',
            'App\\Kernel::terminate' => '?',
            'kernel::loadRoutes' => '?',
            'kernel::registerContainerConfiguration' => '?',
            'kernel::terminate' => '?',
            'App\\Controller\\UsuariosController:delete' => '?',
            'App\\Controller\\UsuariosController:edit' => '?',
            'App\\Controller\\UsuariosController:index' => '?',
            'App\\Controller\\UsuariosController:show' => '?',
            'kernel:loadRoutes' => '?',
            'kernel:registerContainerConfiguration' => '?',
            'kernel:terminate' => '?',
        ]);
    }
}
