<?php

namespace ContainerXV4xLKH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_N4RRAH8Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.n4RRAH8' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.n4RRAH8'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'usuariosRepository' => ['privates', 'App\\Repository\\UsuariosRepository', 'getUsuariosRepositoryService', true],
        ], [
            'usuariosRepository' => 'App\\Repository\\UsuariosRepository',
        ]);
    }
}
