<?php

namespace ContainerXV4xLKH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getUsuariosService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator._8HzjRM.App\Entity\Usuarios' shared service.
     *
     * @return \App\Entity\Usuarios
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator._8HzjRM": it references class "App\\Entity\\Usuarios" but no such service exists.');
    }
}
