<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXV4xLKH\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXV4xLKH/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXV4xLKH.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXV4xLKH\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXV4xLKH\App_KernelDevDebugContainer([
    'container.build_hash' => 'XV4xLKH',
    'container.build_id' => 'ca4cdbd9',
    'container.build_time' => 1601581396,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXV4xLKH');
